using CustomList.Collections;
//MyList<string> ListInt = new MyList<string>();
MyList<int> ListInt = new MyList<int>();
//ListInt.Add("asds");
//ListInt.Add("adsf");
//ListInt.Add("dasfasd");
//ListInt.Add("jtyy");
//ListInt.Add("3q5r");
//ListInt.Add("eutrw");
//ListInt.Add("shjyd");
ListInt.Add(5);
ListInt.Add(2);
ListInt.Add(24);
ListInt.Add(6);
ListInt.Add(3);
ListInt.Add(9);
ListInt.Sort();
ListInt.Reverse();
ListInt.Find(x => x == 1);
ListInt.Remove(1);
ListInt.Contains(1);
ListInt.Sort();
//ListInt.Clear();
foreach (int item in ListInt)
    Console.WriteLine(item);
List<int> list = new List<int>();   
list.Sort();
